### ISSUE TITLE
Compiler Crash

### ISSUE THREAD

**Issue by AbyssMorgan** [Pottus/ColAndreas#23]
Hi, if someone tries to add colandreas.inc, and not adding streamer.inc before colandreas, then compiler crashing.

Example:
//#include <streamer>
#include <ColAndreas>

Compiler crash

Fix:
#if !defined Streamer_AppendArrayData
	#error Unknown Streamer Version
#endif

**Comment by Crayder** [comment]
Yeah, that's the point.

**Comment by Crayder** [comment]
So the fix is to use the latest version of streamer? Then we don't need to address it. That's the user's fault since they are using outdated stuff.

Streamer isn't supposed to be required in ColAndreas, the streamer functions in the ColAndreas include are just wrappers to make the user's work easier.

**Comment by AbyssMorgan** [comment]
The point is that colandreas.inc crashuje compiler is missing since streamer.inc contains additional option I can see how to fix it. I added a condition that checks whether the added streamer.inc you might as well check whether is defined CreateDynamicObject.
#if !defined CreateDynamicObject
#error Unknown Streamer Version
#endif
So soon I will deal with testing and finding the problem.

**Comment by Crayder** [comment]
That's fine, as long as we aren't forcing it.

Though, since you included the new streamer parameters (which I though I already did), you may want to make sure the latest streamer version (or better) is included.
