### ISSUE TITLE
[Suggestion]CA_MoveObject

### ISSUE THREAD

**Issue by Romz24** [Pottus/ColAndreas#65]
I propose to add this feature. At the moment, without it, it is difficult to make a collision check with gates, doors and elevators.

**Comment by Crayder** [comment]
The problem is MoveObject is not synced for every player that well, and it is client-side. The only way we have to find an estimate of the current position of the object is time, but again it's not the same for each player and will be delayed a small bit no matter what.

The ultimate solution is synced physics such as the physics include by PeppeAC, within the plugin. The problem with this is network and speed limitations. It will NOT look as smooth as a client side object moving, but it's not terrible. Players will not be able to surf these objects either, we could simulate surfing but it would likely be bad due to our limits. It is the ultimate solution, and has been done before but could be improved upon, check out "cimulator" in the meantime.

**Comment by Romz24** [comment]
cimulator - It has not been updated for more than 3 years, there may be serious problems or errors. Also, the fact that no one uses it is very alarming.

**Comment by Crayder** [comment]
I said check it out, it works fine as far as I know. You may have to download from an older commit and compile it yourself though.

**Comment by Pottus** [comment]
You can do this yourself very easily just by using the position / rotation of the moving object then creating a collision object in ColAndreas then just do a raycast.

**Comment by Pottus** [comment]
You can do this yourself very easily just by using the position / rotation of the moving object then creating a collision object in ColAndreas then just do a raycast.
