### ISSUE TITLE
Tried to reload Map

### ISSUE THREAD

**Issue by Pe4en9** [Pottus/ColAndreas#85]
What this a problem? Tried reload server of command /rcon gmx, and console writted text: **tried to reload map...**

**Comment by Crayder** [comment]
Every time you start or restart the server, certain callbacks are called in the plugin to let the plugin know the server is starting up. In this callback we load the collision map into the plugin's memory.

When you "gmx" the server doesn't unload plugin's. So, when this callback is called, we don't allow reloading the map because the map is already in the plugins memory still.

**Comment by Pe4en9** [comment]
Hm, okay, but how to correct it?

**Comment by Crayder** [comment]
It's not an error, it's just a message letting you know the map was already previously loaded into the memory. If you need objects to be removed when you restart, remove them before you restart the server with tracked dynamic ID's.
